clash/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'app.views.home', name='home'),
	url(r'^feeds/(.*)$', 'app.views.feeds'),
	url(r'^mom/(.*)$', 'app.views.mom'),
	url(r'^cmom/(.*)$', 'app.views.cmom'),
	url(r'^ctasks/(.*)$', 'app.views.ctasks'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accept/(.*)$', 'app.views.accept_task'),
    url(r'^submit/(.*)$', 'app.views.submit_task'),
    url(r'^alltasks/(.*)$', 'app.views.alltask'),
    url(r'^mytasks/(.*)$', 'app.views.mytask'),
    url(r'generatefile/(.*)$', 'app.views.generate_file'),
    url(r'logout/$', 'app.views.logout'),
    url(r'comment/(.*)$', 'app.views.comment'),
)

app/models.py
from django.db import models

class Team(models.Model):
	team_id = models.AutoField(primary_key=True)
	team_name = models.CharField(max_length=30)
	def __unicode__(self):
	    return self.team_name

class User(models.Model):
	user_id = models.AutoField(primary_key = True)
	uname = models.CharField(max_length=20)
	passwd = models.CharField(max_length=20)
	ses_id = models.CharField(max_length=16)
	files_path = models.CharField(max_length=16)
	def __unicode__(self):
	    return self.uname

class Task(models.Model):
	task_id = models.AutoField(primary_key=True)
	task_name = models.CharField(max_length=50)
	tags = models.CharField(max_length=150)
	team = models.ForeignKey(Team)
	created_by = models.ForeignKey(User, related_name="created_by")
	assigned_to = models.ForeignKey(User, related_name="assigned_to")

	created_time = models.DateTimeField(auto_now_add=True)
	deadline_time = models.DateTimeField()
	submittion_time = models.DateTimeField(auto_now_add=True)
	accepted_time = models.DateTimeField(auto_now_add=True)
	last_modified_time = models.DateTimeField(auto_now_add=True)

	submitted = models.BooleanField(default=False)
	accepted = models.BooleanField(default=False)
	def __unicode__(self):
	    return self.task_name

class MOM(models.Model):
	mom_id = models.AutoField(primary_key=True)
	subject = models.CharField(max_length=200)
	text = models.CharField(max_length=2000)
	team = models.ForeignKey(Team)
	created_by = models.ForeignKey(User)
	def __unicode__(self):
		return self.subject

class Comments(models.Model):
	comment_id = models.AutoField(primary_key=True)
	task = models.ForeignKey(Task)
	user = models.ForeignKey(User)
	date = models.DateTimeField(auto_now_add=True)
	text = models.CharField(max_length=1000)
	def __unicode__(self):
		return str(self.comment_id)

class File(models.Model):
	file_id = models.AutoField(primary_key=True)
	file_name = models.CharField(max_length=30)
	tags = models.CharField(max_length=150)
	task = models.ForeignKey(Task)
	accepted = models.BooleanField(default=False)
	submitted_time = models.DateTimeField(auto_now_add=True)
	accepted_time = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
		return self.file_name

class Permissions(models.Model):
    per_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User)
    team = models.ForeignKey(Team)
    admin_status = models.BooleanField()
    file_access = models.BooleanField()
    def __unicode__(self):
        t_str = ""
        if self.admin_status==True:
            t_str=" - admin"
        elif self.file_access==True:
            t_str=" - file_access"
        else:
            t_str=" - view"
        return str(self.user)+": "+str(self.team)+t_str

app/templates/home/alltask.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>All Tasks</title>
<link rel="stylesheet" type="text/css" href="/static/task.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<body>
<div class="myHead">
<div class="jumbotron">
      <h1>Clash Workspace : {{round}}</h1>
      <p>Work. Eat. Repeat.</p>
      <p></p>
</div>

{% for task in tasks %}
    <script>
        $(document).ready(function()
        {
          $('#div{{task.task_id}}').hide();
          $("#btn{{task.task_id}}").click(function()
          {
            var link = $(this);
            $("#div{{task.task_id}}").toggle("1.5", function()
            {
                if ($(this).is(':visible')) {
                     link.text('Collapse');
                } else {
                     link.text('Expand');
                }
            });
          });
        });
    </script>
{% endfor %}

<script>
	function fun(file_id,file_name,file_path)
	{
		var xmlhttp;
		xmlhttp=new XMLHttpRequest();
		xmlhttp.open("POST","/generatefile/{{team}}",true);
		xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
		xmlhttp.send("file_id="+file_id.toString()+";username={{user.uname}};sesid={{user.ses_id}}");
		xmlhttp.onreadystatechange=function()
		{
			if(xmlhttp.readyState==4&&xmlhttp.status==200)
			{
				// alert("path: "+"/static/files/"+file_path+"/"+file_name);
				window.location.href = "/static/files/"+file_path+"/"+file_name;
				//$(this).attr({'href':"/static/files/"+file_path+"/"+file_name,'target':'_blank'});
			}
		}
	}
</script>


<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Clash '14</a>
          </div>

          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="../feeds/{{ team }}">Feeds</a></li>

              <li><a href="../mom/{{ team }}">M.O.Ms</a></li>
              <li class="active"><a href="../alltasks/{{ team }}">All Tasks</a></li>
              <li><a href="../mytasks/{{ team }}">My Tasks</a></li>

            </ul><!--nav navbar-nav-->
            <a href="/logout" class="btn btn-small btn-primary pull-right">Logout</a>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
</div><!--/.nsv inverse-->
</div><!--/.myHead -->

<div class="form-horizontal">
    <fieldset>
        <legend>
        	All Tasks
        	{% if is_admin %}
				<a  href="/ctasks/{{team}}" class="btn btn-small btn-success pull-right">New Task</a>
			{% endif %}
        </legend>

        {% for task in tasks %}
        <!--one MOM conntainer-->
        <div class="container">
		    <div class="control-group">

		      <div class="row">
		        <div class="col-lg-6">
		          <h1>{{task.task_name}} : {{task.assigned_to}} </h1>
		     	</div>
		       </div>


		        <!--status checkboxes -->
		        <div class="row">
				  <div class="col-lg-5">
					<div class="input-group">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" class="form-control" value="Created: {{task.created_time}}" disabled="disabled">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-4 -->

				  	<div class="col-lg-4">
					  <div class="input-group">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" class="form-control" value="Deadline: {{task.deadline_time}}" disabled="disabled">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-4-->

				  {% if not task.submitted %}
				  <div class="row">
				    <div class="col-lg-2">
				      <a class="btn btn-small btn-default pull-left" disabled="disabled">Not submitted</a>
				    </div><!-- /.col-lg-6-->
				  {% endif %}

				  {% if task.submitted and not task.accepted %}
				      {% if not is_admin %}
						  <div class="row">
							<div class="col-lg-2">
							  <a class="btn btn-small btn-warning pull-left" disabled="disabled">Under review</a>
							</div><!-- /.col-lg-6-->
					  {% else %}
						  <div class="row">
						  <form action="./{{team}}" method="post">
						  <input type="hidden" name="task_id" value="{{task.task_id}}">
							<div class="col-lg-2">
							<input type="hidden" name="accept" value="accept">
							  <input type="submit" class="btn btn-small btn-warning pull-left" value="Accept">
							</div><!-- /.col-lg-6-->
						   </form>
					  {% endif %}
				  {% endif %}

				  {% if task.accepted %}
				  <div class="row">
				    <div class="col-lg-2">
				      <a class="btn btn-small btn-success pull-left" disabled="disabled">Accepted</a>
				    </div><!-- /.col-lg-6-->
				  {% endif %}

                    <div class="col-lg-1">
				        <button type="button" class="btn btn-default" id="btn{{task.task_id}}">
                            Expand
                        </button>
                    </div>
				</div><!--/.row -->
				<br>

                <div id="div{{task.task_id}}">
				{% for file in task.file_set.all %}
				  <div class="row">
				    <div class="col-lg-2">
				      <a class="btn btn-small btn-default pull-left" disabled="disabled"><b>{{ file.file_name }}</b></a>
				    </div><!-- /.col-lg-6-->

				    <div class="col-lg-3">
				      <a class="btn btn-small btn-default pull-left" disabled="disabled"><b>{{ file.tags }}</b></a>
				    </div><!-- /.col-lg-6-->


				    <div class="col-lg-3">
					<div class="input-group pull-right">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" class="form-control" value="{{file.submitted_time}}" disabled="disabled">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-2 -->
				  <div class="col-lg-1 pull-left">
				    {% if download %}
					  <a onclick="fun({{file.file_id}},'{{file.file_name}}','{{user.files_path}}')" class="btn btn-small btn-custom-deep pull-left">Download</a>
					  {% endif %}
					</div><!-- /.col-lg-1-->

					{% if file.accepted %}
					    <div class="col-lg-1 pull-left">
					  		<a class="btn btn-small btn-success pull-left" disabled="disabled">Accepted</a>
						</div><!-- /.col-lg-1-->
						<!-- green button -->
					{% else %}
						{% if not is_admin %}
							<div class="col-lg-1 pull-left">
						  		<a class="btn btn-warning pull-left" disabled="disabled">Reviewing</a>
							</div><!-- /.col-lg-1-->
							<!-- orange button -->
						{% else %}
							<form action="./{{team}}" method="post">
								<input type="hidden" name="file_id" value="{{file.file_id}}">
								<div class="col-lg-1 pull-left">
							  		<input type="submit" class="btn btn-warning pull-left" value="Accept">
								</div><!-- /.col-lg-1-->
								<!-- orange button -->
							</form>
						{% endif %}
					{% endif %}

				  </div><!-- /.ROW-->
				 <br>
				 {% endfor %}

			<!--panel for posting previous comments-->
		        <p></p>
		        <div class="panel panel-default">
				  <div class="panel-heading"><b>Comments</b></div>

				   {% for comment in task.comments_set.all %}
				    <div class="panel-body">
				      <b>{{comment.user}}: </b>{{comment.text}} <div style="float:right">{{comment.date}}</div>
				    </div>
				   {% endfor %}

				  </div>

		        	<!--comments area-->
		        	<p></p>
		        	<lable for="user_id" class="btn btn-small btn-default pull-left" disabled="disabled"><b>Comment</b></lable>
		        	<form action="./{{team}}" method="post">
		        		<input type="hidden" name="task_id" value="{{task.task_id}}">
						<div class ="col-lg-10">
							<input class="form-control focusedInput" type="text" name="text" placeholder="Post comment here...">
						</div>
						<div class="col-lg-1 pull-left">
						  <input type="submit" value="Submit" class="btn btn-small btn-success pull-left">
						</div>
					</form>
					<br>
					<hr>

        <hr>
        </div><!--/.container -->

        </div>
        </div>
        </div>

        {% endfor %}
    </fieldset>
</div>

app/templates/home/choice.html
<!DOCTYPE html>
<head>
<title>Admins</title>
<link rel="stylesheet" type="text/css" href="/static/admin.css">
</head>
<body>
<div class="adHead">
   <div class="jumbotron">
      <h1>Clash Workspace!</h1>
      <p>Work. Eat. Repeat.</p>
      </p>
   </div>
</div>
<div class="container">
	<div class="myRow">
        {% for team in teams %}
			<a href="/feeds/{{team.team_name}}">
			<img src='/static/{{team.team_name}}.png' width="300" >
			</a>
        {% endfor %}

	</div>
</div>

app/templates/home/cmom.html
<html>
	<title>New MOM</title>
	<form action="/cmom/{{ team }}" method="POST">
		<textarea placeholder="Meeting date and time" style="height:10%;width:40%" name="subject"></textarea><br/><br/>
		<textarea placeholder="MOM" style="height:20%;width:40%" name="text"></textarea><br/><br/>
		<input style="height:4%;width:10%" type="submit">
	</form>
</html>

app/templates/home/ctasks.html
<html>
	<title>New task</title>
	<form action="/ctasks/{{ team }}" method="POST">
		<textarea placeholder="task name" style="height:10%;width:40%" name="task_name"></textarea><br/><br/>
		<textarea placeholder="tags" style="height:10%;width:40%" name="tags"></textarea><br/><br/>

		<b>Assigned to:</b>
		<select name="assigned_to">
			{% for user in users %}
				<option name="{{user.uname}}">{{user}}</option>
			{% endfor %}
			{% for user in admins %}
				<option name="{{user.uname}}">{{user}}</option>
			{% endfor %}
		</select>
		<pre><b>Deadline:</b>    <input type="datetime-local" name="deadline"><br/><br/></pre>
		<input style="height:4%;width:10%" type="submit">
	</form>
</html>

app/templates/home/feed.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Clash Feeds</title>
<link rel="stylesheet" type="text/css" href="/static/feed.css">
</head>
<body>
<div class="myHead">
<div class="jumbotron">
      <h1>Clash Workspace : {{round}}</h1>
      <p>Work. Eat. Repeat.</p>
      <p></p>
</div>

<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Clash '14</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="../feeds/{{ team }}">Feeds</a></li>

              <li><a href="../mom/{{ team }}">M.O.Ms</a></li>
              <li><a href="../alltasks/{{ team }}">All Tasks</a></li>
              <li><a href="../mytasks/{{ team }}">My Tasks</a></li>
            </ul>
            <a href="/logout" class="btn btn-small btn-primary pull-right">Logout</a>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
</div><!--/.nsv inverse-->
</div><!--/.myHead -->

<div class="form-horizontal">
    <fieldset>
        <legend>
        	Feed Updates
        	{% if isadmin %}
				<a  href="/ctasks/{{team}}" class="btn btn-small btn-success pull-right">New Task</a>
			{% endif %}
        </legend>
        {% block content %}
		{% for task in tasks %}
		    <!--start of feed conntainer-->
		    <div class="container">
				<div class="control-group">
				    <label class="control-label">Task id: {{task.task_id}} : {{ task.last_modified_time }}</label>
				    <div class="controls">
				        <p class="form-control-static"> <pre>{{task.task_name}}</pre>
				<pre>Assigned to: {{task.assigned_to}}
Created by: {{task.created_by}}</pre>
				        </p>
				        <p></p>
				    </div>

				    <div class="row">

					  <!--div class="col-lg-4">
						<div class="input-group">
						  Assigned to: {{task.assigned_to}}
						</div><!-- /input-group >
					  </div><!-- /.col-lg-4 -->

				    <!--status checkboxes -->
					  <div class="col-lg-4">
						<div class="input-group">
						  <span class="input-group-addon">
						  	{% if not task.submitted %}
								<span class="glyphicon glyphicon-ok"></span>
							{% else %}
								<input type="checkbox" disabled="disabled"><!--chenge checked to set-->
							{% endif %}
						  </span>
						  <input type="text" class="form-control" value="Not submitted" disabled="disabled">
						</div><!-- /input-group -->
					  </div><!-- /.col-lg-4 -->
					  <div class="col-lg-4">
						  <div class="input-group">
						  <span class="input-group-addon">
						  	{% if task.submitted and not task.accepted %}
								<span class="glyphicon glyphicon-ok"></span>
							{% else %}
								<input type="checkbox" disabled="disabled"><!--chenge checked to set-->
							{% endif %}						  </span>
						  <input type="text" class="form-control" value="Under Review" disabled="disabled">
						</div><!-- /input-group -->
					  </div><!-- /.col-lg-4 -->
					  <div class="col-lg-4">
						<div class="input-group">
						  <span class="input-group-addon">
						  	{% if task.accepted %}
								<span class="glyphicon glyphicon-ok"></span>
							{% else %}
								<input type="checkbox" disabled="disabled"><!--chenge checked to set-->
							{% endif %}						  </span>
						  <input type="text" class="form-control" value="Accepted" disabled="disabled">
						</div><!-- /input-group -->
					  </div><!-- /.col-lg-6 -->
				    </div>
				    	<!--panel for posting previous comments-->
				</div><!--/.control-group -->
		    </div><!--/.container -->

		    <!--end of MOM conntainer-->
		    <br/><br/>

        {% endfor %}
        {% endblock %}
    </fieldset>
</div>

app/templates/home/home.html
<html>
    <script>
        function func()
        {
            window.location="/feeds/{{team}}"
        }
    </script>
    <body onload="func()">
        Logging you in...
    </body>
</html>

app/templates/home/mytask.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>My Tasks</title>
<link rel="stylesheet" type="text/css" href="/static/task.css">
<script src="/static/jq.js"></script>

{% for task in tasks %}
    <script>
        $(document).ready(function()
        {
          $('#div{{task.task_id}}').hide();
          $("#btn{{task.task_id}}").click(function()
          {
            var link = $(this);
            $("#div{{task.task_id}}").toggle("1.5", function()
            {
                if ($(this).is(':visible')) {
                     link.text('Collapse');
                } else {
                     link.text('Expand');
                }
            });
          });
        });
        </script>
{% endfor %}

<script>
	function fun(file_id,file_name,file_path)
	{
		var xmlhttp;
		xmlhttp=new XMLHttpRequest();
		xmlhttp.open("POST","/generatefile/{{team}}",true);
		xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
		xmlhttp.send("file_id="+file_id.toString()+";username={{user.uname}};sesid={{user.ses_id}}");
		xmlhttp.onreadystatechange=function()
		{
			if(xmlhttp.readyState==4&&xmlhttp.status==200)
			{
				// alert("path: "+"/static/files/"+file_path+"/"+file_name);
				window.location.href = "/static/files/"+file_path+"/"+file_name;
				//$(this).attr({'href':"/static/files/"+file_path+"/"+file_name,'target':'_blank'});
			}
		}
	}
</script>

<!--script>
	var cook=document.cookie;
	var tp=cook.indexOf("name=");
	var tosend=cook.substring(tp+5);
	var xmlhttp;
	xmlhttp=new XMLHttpRequest();
	xmlhttp.open("POST","cques.php",true);
	xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xmlhttp.send("name="+tosend);
	xmlhttp.onreadystatechange=function()
	{
		if(xmlhttp.readyState==4&&xmlhttp.status==200)
		{
			document.getElementById("newdiv").innerHTML=xmlhttp.responseText+"  ";
			var a=document.createElement('a');
			a.href="http://localhost/clash/view";
			a.innerText="view";
			document.getElementById("newdiv").appendChild(a);
		}
	}
</script-->

</head>
<body>
<div class="myHead">
<div class="jumbotron">
      <h1>Clash Workspace : {{round}}</h1>
      <p>Work. Eat. Repeat.</p>
      <p></p>
</div>

<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Clash '14</a>
          </div>

          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="../feeds/{{ team }}">Feeds</a></li>
              <li><a href="../mom/{{ team }}">M.O.Ms</a></li>
              <li><a href="../alltasks/{{ team }}">All Tasks</a></li>
              <li class="active"><a href="../mytasks/{{ team }}">My Tasks</a></li>
			  </ul>
			 </li>
            </ul><!--nav navbar-nav-->
            <a href="/logout" class="btn btn-small btn-primary pull-right">Logout</a>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
</div><!--/.nsv inverse-->
</div><!--/.myHead -->

<div class="form-horizontal">
    <fieldset>
        <legend>
        	My Tasks
        	{% if is_admin %}
				<a  href="/ctasks/{{team}}" class="btn btn-small btn-success pull-right">New Task</a>
			{% endif %}
        </legend>

        {% for task in tasks %}
        <!--one MOM conntainer-->
        <div class="container">
		    <div class="control-group">

		      <div class="row">
		        <div class="col-lg-6">
		          <h1>{{ task.task_name }}</h1>
		     	</div>
		       </div>


		        <!--status checkboxes -->
		        <div class="row">
				  <div class="col-lg-5">
					<div class="input-group">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" class="form-control" value="Created: {{ task.created_time }}" disabled="disabled">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-4 -->

				  	<div class="col-lg-4">
					  <div class="input-group">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" class="form-control" value="Deadline: {{task.deadline_time}}" disabled="disabled">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-4-->

				  				  {% if not task.submitted %}
				  <div class="row">
				    <div class="col-lg-2">
				      <a class="btn btn-small btn-default pull-left" disabled="disabled">Not submitted</a>
				    </div><!-- /.col-lg-6-->
				  {% endif %}

				  {% if task.submitted and not task.accepted %}
						  <div class="row">
							<div class="col-lg-2">
							  <a class="btn btn-small btn-warning pull-left" disabled="disabled">Under review</a>
							</div><!-- /.col-lg-6-->

				  {% endif %}

				  {% if task.accepted %}
				  <div class="row">
				    <div class="col-lg-2">
				      <a class="btn btn-small btn-success pull-left" disabled="disabled">Accepted</a>
				    </div><!-- /.col-lg-6-->
				  {% endif %}

                    <div class="col-lg-1">
				        <button type="button" class="btn btn-default" id="btn{{task.task_id}}">
                            Expand
                        </button>
                    </div>

				</div><!--/.row -->
				<br>

                <div id="div{{task.task_id}}">
				{% for file in task.file_set.all %}
				  <div class="row">
				    <div class="col-lg-2">
				      <a class="btn btn-small btn-default pull-left" disabled="disabled"><b>{{ file.file_name }}</b></a>
				    </div><!-- /.col-lg-6-->

				    <div class="col-lg-3">
				      <a class="btn btn-small btn-default pull-left" disabled="disabled"><b>{{ file.tags }}</b></a>
				    </div><!-- /.col-lg-6-->


				    <div class="col-lg-3">
					<div class="input-group pull-right">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" class="form-control" value="{{file.submitted_time}}" disabled="disabled">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-2 -->
				  <div class="col-lg-1 pull-left">
					  <a onclick="fun({{file.file_id}},'{{file.file_name}}','{{user.files_path}}')" class="btn btn-small btn-custom-deep pull-left">Download</a>
					</div><!-- /.col-lg-1-->

					{% if file.accepted %}
					    <div class="col-lg-1 pull-left">
					  		<a class="btn btn-small btn-success pull-left" disabled="disabled">Accepted</a>
						</div><!-- /.col-lg-1-->
						<!-- green button -->
					{% else %}
						<div class="col-lg-1 pull-left">
					  		<a class="btn btn-warning pull-left" disabled="disabled">Reviewing</a>
						</div><!-- /.col-lg-1-->
						<!-- orange button -->
					{% endif %}

				  </div><!-- /.ROW-->
				 <br>
				 {% endfor %}
                </div>
				  <hr 	style="height:1px">


				</div>
				  <!--upload button-->

		      <form action="./{{team}}" enctype="multipart/form-data"  method="post">
		      <div class="row">
		      <div class="col-lg-5">
		          <a class="btn btn-small btn-default pull-left" disabled="disabled"><b>Upload new file</b></a>
		     	</div>



		        <div class="col-lg-3">
					<div class="input-group">
					  <span class="input-group-addon">
						<span class="glyphicon glyphicon-ok"></span>
					  </span>
					  <input type="text" name="tags" class="form-control" placeholder="Created by">
					</div><!-- /input-group -->
				  </div><!-- /.col-lg-3 -->

				<div class="col-lg-1">
				    <div class="fileupload fileupload-new" data-provides="fileupload">
						<span class="btn btn-primary btn-file">
							<span class="fileupload-new">
								Select file
							</span>
							<span class="fileupload-exists">
								Change
							</span>
							<input type="hidden" name="task_id" value="{{task.task_id}}">
							<input type="file" name="file_submit">
						</span>
						<span class="fileupload-preview"></span>
						<a href="#" class="close fileupload-exists" data-dismiss="fileupload" style="float: none">×</a>
					</div>
				</div><!-- /.col-lg-1 -->

				<div class="col-lg-1 pull-left">
					  <input type="submit" class="btn btn-small btn-success pull-left" value="&nbsp;&nbsp;Upload&nbsp;&nbsp;">
				</div>
			</div><!--row-->
			</form>
			</div><!--/.control-group -->
        </div><!--/.container -->
        <hr>
        {% endfor %}



    </fieldset>
</div>

app/templates/home/tasks.html
<html>
	<title>New task</title>
	{% for task in tasks %}
		<b> Task id: {{task.task_id}} | </b>
		<b> {{task.task_name}}</b><br/>
		Assigned To: {{task.assigned_to}}
		<form action="/submit/{{team}}" enctype="multipart/form-data" method="post">
			<input type="hidden" name="task_id" value="{{task.task_id}}">
			<input type="file" name="file_submit">
			<input type="submit" value="upload">
		</form>
	{% endfor %}
</html>